### ISSUE TITLE
Temasys/AdapterJS

### ISSUE THREAD

**Issue by discoveryjames** [priologic/easyrtc#306]
I've built the easyrtc.js file without the adapter and replace it with the Temasys/AdapterJS adapter as recommended in the closed issue.

I still can't seem to get them to work together, I get the error:

Type Error on createObjectURL

Any ideas?

**Comment by EricDavies** [comment]
If you send me the Temasys/AdapterJS, I'll see how they are trying to attach the media stream to the video object.

**Comment by discoveryjames** [comment]
Hi EricDavies,

Thanks for getting back to me.

https://github.com/Temasys/AdapterJS is what I'm using.

By stripping out the easyRTC adapter and replacing it with Temasys/AdapterJS it hasn't prevented it from working in Chrome/Firefox.

It half works in Safari, the prompt shows to ask which camera and microphone to access, then the camera light comes on the laptop. So it seems to get right up until the point of attaching the video stream, I think a small modification is required to easyRTC to allow it to attach the media steam, but I can't work out what.

Any suggestions would be much appreciated.

**Comment by EricDavies** [comment]
From what I can see, Temasys supplies a method called attachMediaStream(element, stream). I don't see anywhere that this is associated with a setter method so I assume you are expected to call this method from your application or tool kit.
As a test, modify the demo called "Audio and Video". It attaches the media stream explicitly to the video object with code that looks like:

easyrtc.setStreamAcceptor( function(easyrtcid, stream) {
  setUpMirror();
  var video = document.getElementById("callerVideo");
  easyrtc.setVideoObjectSrc(video,stream);
  enable("hangupButton");
});

Change that to:

easyrtc.setStreamAcceptor( function(easyrtcid, stream) {
  setUpMirror();
  var video = document.getElementById("callerVideo");
  window.attachMediaStream(video,stream);
  enable("hangupButton");
});

If that works, I can modify the easyrtc.js file to explicitly use attachMediaStream if it is found.

**Comment by discoveryjames** [comment]
Hi EricDavies,

I've tried this, but unfortunately seemed to get the same problem. 

My code varies slightly to yours, but is mostly the same. One thing which might be causing problems is easyrtc.getLocalStream(), as this probably isn't being ran through Temasys adapter.

**Comment by EricDavies** [comment]
what value does stream have when you reach attachMediaStream?

**Comment by hthetiot** [comment]
I used Temasys plugin with easyrtc in the past on IE and Safari. No easyrtc was needed.

**Comment by chpasha** [comment]
Temasys plugin works fine with easyrtc...sort of. Two JSON.stringify calls below cause IE to freeze because the candidate objects returned from plugin are not serializeable

function iceAddSuccess() {
                logDebug("iceAddSuccess: " +
                    JSON.stringify(candidate));
                processCandicate(msgData.candidate);
            }

            function iceAddFailure(domError) {
                self.showError(self.errCodes.ICECANDIDATE_ERR, "bad ice candidate (" + domError.name + "): " +
                    JSON.stringify(candidate));
            }

**Comment by EricDavies** [comment]
I've just applied chpasha's fix to the zombieland branch.
There were a few places where somebody has spelt candidate as candicate (but consistently) which I also fixed.

**Comment by discoveryjames** [comment]
Does anyone have an example of this working?

I still can't seem to get them to work together, I get the error:

Type Error on createObjectURL

**Comment by hthetiot** [comment]
we only use createObjectURL when srcObject is not available.
See webrtc adapter for plugin support.
